from dataclasses import dataclass, field


@dataclass(slots=True)
class LLMResponse:
    """
    Response generated by an LLM.
    """

    answer: str

    metadata: dict[str, str] = field(default_factory=dict)
